apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-data-pvc
  namespace: liferay-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: liferay-deploy-pvc
  namespace: liferay-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-osgi-modules-pvc
  namespace: liferay-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-logs-pvc
  namespace: liferay-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage